import requests
from bs4 import BeautifulSoup
from splinter import Browser
from datetime import date
import time
from pandas import DataFrame
from selenium import webdriver
import re
import os
from calendar import monthrange
import datetime
import os.path
from selenium.webdriver import DesiredCapabilities
from selenium.webdriver.support.ui import Select

# global variable definition
domain = 'http://www.vegasinsider.com'
name_vegas = [
    'Akron',
    'Alabama',
    'Alabama',
    'Alabama A&M',
    'Albany',
    'American University',
    'Appalachian State',
    'Appalachian State',
    'Arizona',
    'Arizona State',
    'Arkansas',
    'Arkansas State',
    'Arkansas-Little Rock',
    'Army',
    'Auburn',
    'Austin Peay',
    'Ball State',
    'Baylor',
    'Belmont',
    'Boise State',
    'Boston College',
    'Bowling Green',
    'Bradley',
    'Brown',
    'Bucknell',
    'SUNY-Buffalo',
    'Butler',
    'BYU',
    'Cal Poly',
    'Cal State Bakersfield',
    'CS Fullerton',
    'CS Northridge',
    'California',
    'Canisius',
    'Central Connecticut State',
    'Central Michigan',
    'Chaminade',
    'Charleston',
    'Charlotte',
    'Chattanooga',
    'Cincinnati',
    'Citadel',
    'Clemson',
    'Cleveland State',
    'Coastal Carolina',
    'Colorado',
    'Colorado State',
    'Columbia',
    'Connecticut',
    'Coppin State',
    'Cornell',
    'Creighton',
    'Dartmouth',
    'Davidson',
    'Dayton',
    'Delaware',
    'Denver',
    'DePaul',
    'Detroit',
    'Drexel',
    'Duke',
    'Duquesne',
    'East Carolina',
    'East Tennessee St.',
    'Eastern Illinois',
    'Eastern Kentucky',
    'Eastern Michigan',
    'Eastern Washington',
    'Elon',
    'Evansville',
    'Fairfield',
    'Florida',
    'Florida Atlantic',
    'Florida Gulf Coast',
    'Florida Intl',
    'Florida State',
    'Fordham',
    'Fresno State',
    'Furman',
    'George Mason',
    'George Washington',
    'Georgetown',
    'Georgia',
    'Georgia Southern',
    'Georgia State',
    'Georgia Tech',
    'Gonzaga',
    'Grambling State',
    'Grand Canyon',
    'Green Bay',
    'Hartford',
    'Harvard',
    'Hawaii',
    'Hofstra',
    'Holy Cross',
    'Houston',
    'Howard',
    'Idaho',
    'Idaho State',
    'Illinois',
    'Illinois State',
    'Illinois-Chicago',
    'Indiana',
    'Indiana State',
    'Iona',
    'Iowa',
    'Iowa State',
    'IUPU-Fort Wayne',
    'Indiana-Purdue',
    'Jacksonville State',
    'James Madison',
    'Kansas',
    'Kansas State',
    'Kent State',
    'Kentucky',
    'La Salle',
    'Lafayette',
    'Lamar',
    'CS Long Beach',
    'Longwood',
    'Louisiana Tech',
    'Louisiana-Monroe',
    'Louisville',
    'Loyola-Chicago',
    'Loyola-Marymount',
    'Louisiana State',
    'Manhattan',
    'Marist',
    'Marquette',
    'Marshall',
    'Maryland',
    'Massachusetts',
    'Massachusetts Lowell',
    'Memphis',
    'Mercer',
    'Miami (FL)',
    'Miami (OH)',
    'Miami (OH)',
    'Michigan',
    'Michigan State',
    'Middle Tennessee',
    'Milwaukee',
    'Minnesota',
    'Mississippi State',
    'Missouri',
    'Missouri State',
    'Monmouth',
    'Montana',
    'Montana State',
    'Morehead State',
    'Murray State',
    'New Jersey Tech',
    'Navy',
    'Nebraska',
    'Nebraska-Omaha',
    'Nevada',
    'New Mexico',
    'New Mexico State',
    'Niagara',
    'Norfolk State',
    'North Carolina',
    'North Carolina Central',
    'North Carolina State',
    'UNC Wilmington',
    'North Dakota State',
    'North Texas',
    'Northeastern',
    'Northern Arizona',
    'Northern Colorado',
    'Northern Illinois',
    'Northern Iowa',
    'Northern Kentucky',
    'Northwestern',
    'Northwestern State',
    'Notre Dame',
    'Oakland',
    'Ohio',
    'Ohio State',
    'Oklahoma',
    'Oklahoma State',
    'Old Dominion',
    'Mississippi',
    'Oral Roberts',
    'Oregon',
    'Oregon State',
    'Pacific',
    'Penn State',
    'Pennsylvania',
    'Pepperdine',
    'Pittsburgh',
    'Portland',
    'Portland State',
    'Princeton',
    'Providence',
    'Purdue',
    'Quinnipiac',
    'Rhode Island',
    'Rice',
    'Richmond',
    'Rider',
    'Robert Morris',
    'Rutgers',
    'CS Sacramento',
    'Sacred Heart',
    'St. Louis',
    'Samford',
    'San Diego',
    'San Diego State',
    'San Francisco',
    'San Jose State',
    'Santa Clara',
    'Seattle',
    'Seton Hall',
    'Siena',
    'SIU Edwardsville',
    'Southern Methodist',
    'South Alabama',
    'South Carolina',
    'South Dakota',
    'South Dakota State',
    'South Florida',
    'SE Missouri State',
    'Southern Illinois',
    'Southern Miss',
    'Southern Utah',
    'St. Bonaventure',
    'St. Francis (BKN)',
    "St. John's",
    "Saint Joseph's (PA)",
    'Stanford',
    'Stephen F. Austin',
    'Stony Brook',
    'Syracuse',
    'Texas Christian',
    'Temple',
    'Tennessee',
    'Tennessee State',
    'Tennessee Tech',
    'UT Martin',
    'Texas',
    'Texas AM',
    'Texas State',
    'Texas Tech',
    'Texas-Arlington',
    'Toledo',
    'Towson',
    'Troy',
    'Tulane',
    'Tulsa',
    'UAB',
    'UC Davis',
    'UC Irvine',
    'UC Riverside',
    'UC Santa Barbara',
    'Central Florida',
    'UCLA',
    'UMKC',
    'UNC Greensboro',
    'UNLV',
    'Southern Cal',
    'Utah',
    'Utah State',
    'UTEP',
    'Texas-San Antonio',
    'Valparaiso',
    'Vanderbilt',
    'Vermont',
    'Villanova',
    'Virginia',
    'Virginia Military',
    'Virginia Tech',
    'Wake Forest',
    'Washington',
    'Washington State',
    'Weber State',
    'Western Carolina',
    'Western Illinois',
    'Western Kentucky',
    'Western Michigan',
    'Wichita State',
    'William Mary',
    'Winthrop',
    'Wisconsin',
    'Wofford',
    'Wright State',
    'Wyoming',
    'Xavier',
    'Yale',
    'Youngstown State',
    'Virginia Commonwealth',
    'MD-Baltimore County',
    'North Carolina AT',
    'SE Louisiana',
    'Sam Houston State',
    'Prairie View AM',
    'Alaska-Anchorage',
    'UNC Asheville',
    'Bryant'
]
name_sbr = [
    'Akron',
    'Alabama',
    'Alabama',
    'Alabama A&M',
    'Albany',
    'American University',
    'Appalachian State',
    'Appalachian State',
    'Arizona',
    'Arizona State',
    'Arkansas',
    'Arkansas State',
    'Arkansas-Little Rock',
    'Army',
    'Auburn',
    'Austin Peay',
    'Ball State',
    'Baylor',
    'Belmont',
    'Boise State',
    'Boston College',
    'Bowling Green',
    'Bradley',
    'Brown',
    'Bucknell',
    'Buffalo',
    'Butler',
    'BYU',
    'Cal Poly',
    'Cal State Bakersfield',
    'Cal State Fullerton',
    'Cal State Northridge',
    'California',
    'Canisius',
    'Central Connecticut State',
    'Central Michigan',
    'Chaminade University',
    'Charleston',
    'Charlotte',
    'Chattanooga',
    'Cincinnati',
    'Citadel',
    'Clemson',
    'Cleveland State',
    'Coastal Carolina',
    'Colorado',
    'Colorado State',
    'Columbia',
    'Connecticut',
    'Coppin State',
    'Cornell',
    'Creighton',
    'Dartmouth',
    'Davidson',
    'Dayton',
    'Delaware',
    'Denver',
    'DePaul',
    'Detroit',
    'Drexel',
    'Duke',
    'Duquesne',
    'East Carolina',
    'East Tennessee State',
    'Eastern Illinois',
    'Eastern Kentucky',
    'Eastern Michigan',
    'Eastern Washington',
    'Elon',
    'Evansville',
    'Fairfield',
    'Florida',
    'Florida Atlantic',
    'Florida Gulf Coast',
    'Florida International',
    'Florida State',
    'Fordham',
    'Fresno State',
    'Furman',
    'George Mason',
    'George Washington',
    'Georgetown',
    'Georgia',
    'Georgia Southern',
    'Georgia State',
    'Georgia Tech',
    'Gonzaga',
    'Grambling State',
    'Grand Canyon',
    'Green Bay',
    'Hartford',
    'Harvard',
    'Hawaii',
    'Hofstra',
    'Holy Cross',
    'Houston',
    'Howard',
    'Idaho',
    'Idaho State',
    'Illinois',
    'Illinois State',
    'Illinois-Chicago',
    'Indiana',
    'Indiana State',
    'Iona',
    'Iowa',
    'Iowa State',
    'IPFW',
    'IUPUI',
    'Jacksonville State',
    'James Madison',
    'Kansas',
    'Kansas State',
    'Kent State',
    'Kentucky',
    'La Salle',
    'Lafayette',
    'Lamar',
    'Long Beach State',
    'Longwood',
    'Louisiana Tech',
    'Louisiana-Monroe',
    'Louisville',
    'Loyola (IL)',
    'Loyola Marymount',
    'LSU',
    'Manhattan',
    'Marist',
    'Marquette',
    'Marshall',
    'Maryland',
    'Massachusetts',
    'Massachusetts Lowell',
    'Memphis',
    'Mercer',
    'Miami (FL)',
    'Miami (OH)',
    'Iowa State',
    'Michigan',
    'Michigan State',
    'Middle Tennessee',
    'Milwaukee',
    'Minnesota',
    'Mississippi State',
    'Missouri',
    'Missouri State',
    'Monmouth',
    'Montana',
    'Montana State',
    'Morehead State',
    'Murray State',
    'N.J.I.T.',
    'Navy',
    'Nebraska',
    'Nebraska-Omaha',
    'Nevada',
    'New Mexico',
    'New Mexico State',
    'Niagara',
    'Norfolk State',
    'North Carolina',
    'North Carolina Central',
    'North Carolina State',
    'North Carolina-Wilmington',
    'North Dakota State',
    'North Texas',
    'Northeastern',
    'Northern Arizona',
    'Northern Colorado',
    'Northern Illinois',
    'Northern Iowa',
    'Northern Kentucky',
    'Northwestern',
    'Northwestern State',
    'Notre Dame',
    'Oakland',
    'Ohio',
    'Ohio State',
    'Oklahoma',
    'Oklahoma State',
    'Old Dominion',
    'Ole Miss',
    'Oral Roberts',
    'Oregon',
    'Oregon State',
    'Pacific',
    'Penn State',
    'Pennsylvania',
    'Pepperdine',
    'Pittsburgh',
    'Portland',
    'Portland State',
    'Princeton',
    'Providence',
    'Purdue',
    'Quinnipiac',
    'Rhode Island',
    'Rice',
    'Richmond',
    'Rider',
    'Robert Morris',
    'Rutgers',
    'Sacramento State',
    'Sacred Heart',
    'Saint Louis',
    'Samford',
    'San Diego',
    'San Diego State',
    'San Francisco',
    'San Jose State',
    'Santa Clara',
    'Seattle',
    'Seton Hall',
    'Siena',
    'SIU-Edwardsville',
    'SMU',
    'South Alabama',
    'South Carolina',
    'South Dakota',
    'South Dakota State',
    'South Florida',
    'Southeast Missouri State',
    'Southern Illinois',
    'Southern Miss',
    'Southern Utah',
    'St. Bonaventure',
    'St. Francis (BKN)',
    "St. John's",
    "Saint Joseph's (PA)",
    'Stanford',
    'Stephen F. Austin',
    'Stony Brook',
    'Syracuse',
    'TCU',
    'Temple',
    'Tennessee',
    'Tennessee State',
    'Tennessee Tech',
    'Tennessee-Martin',
    'Texas',
    'Texas A&M',
    'Texas State',
    'Texas Tech',
    'Texas-Arlington',
    'Toledo',
    'Towson',
    'Troy',
    'Tulane',
    'Tulsa',
    'UAB',
    'UC Davis',
    'UC Irvine',
    'UC Riverside',
    'UC Santa Barbara',
    'UCF',
    'UCLA',
    'UMKC',
    'UNC Greensboro',
    'UNLV',
    'USC',
    'Utah',
    'Utah State',
    'UTEP',
    'UTSA',
    'Valparaiso',
    'Vanderbilt',
    'Vermont',
    'Villanova',
    'Virginia',
    'Virginia Military',
    'Virginia Tech',
    'Wake Forest',
    'Washington',
    'Washington State',
    'Weber State',
    'Western Carolina',
    'Western Illinois',
    'Western Kentucky',
    'Western Michigan',
    'Wichita State',
    'William & Mary',
    'Winthrop',
    'Wisconsin',
    'Wofford',
    'Wright State',
    'Wyoming',
    'Xavier',
    'Yale',
    'Youngstown State',
    'Virginia Commonwealth',
    'UMBC',
    'North Carolina A&T',
    'Southeastern Louisiana',
    'Sam Houston State',
    'Prairie View A&M',
    'Alaska Anchorage',
    'UNC Asheville',
    'Bryant University'
]

result_vegas = []
#     return soup
def soup_url_vegas(week):
    url = domain + '/nfl/matchups/matchups.cfm/week/' + week +'/season/2016'
    print(url)
    soup_big = BeautifulSoup(requests.get(url).text, 'html.parser')
    soup = soup_big.find_all('table',width="100%")
    return soup

# Finding all games tables
def g(soup):
    return soup.find_all('td',attrs={'class':'viBodyBorderNorm'})

# Get all rows from games tables
def get_games_links(soup):
    return soup.find_all('tr')

# Get cells with data
def get_game_info(o):
    return o.find_all('td',attrs={'class': "cellTextNorm"})

def parse_to_csv_vegas(week):
    global result_vegas
    sp = BeautifulSoup(str(soup_url_vegas(week)), 'html.parser')
    # Result list
    a = []
    for uis in g(sp):
        for bt_mouvment_page in get_games_links(uis):
            # array to fill with data of each row
            # day = ('0' if len(str(date.day)) == 1 else '') + str(date.day)
            # month = ('0' if len(str(date.month)) == 1 else '') + str(date.month)
            # year = ('0' if len(str(date.year)) == 1 else '') + str(date.year)            

            d = [week]
            if get_game_info(bt_mouvment_page) != None:

                for i in get_game_info(bt_mouvment_page):
                    # team name
                    if i.a:
                        d.append(i.a.string.strip())
                    elif i.string == None:
                        d.append('NaN')
                    elif i.string.strip() == '' :
                        d.append('NaN')
                    # Data
                    else:
                        d.append(i.string.strip())
            if len(d) > 2:            
                print('result=> ',d)
            # if len(d) > 2:
            #     if (len(d) == 13):
            #         d.append('NaN')
            #     a.append(','.join(d) + '\n')
            #     #########################################
            #     # add sbr name
            #     nameBySbr = d[2]
            #     for k in range(len(name_vegas)):
            #         if name_vegas[k] == d[2]:
            #             nameBySbr = name_sbr[k]
            #             print(name_sbr[k])
            #             break
            #     d.append(nameBySbr)
            #     print(d)
            #     result_vegas.append(d)
            #     ##############################################
            #     with open('ncaa_vegasinsider.csv', 'a') as t:
            #         t.write(','.join(d) + '\n')



if __name__ == '__main__':

    ##################################################
    # get vegas
    # start_year = input("[VEGAS] Please type the year for which you would like to pull data (yyyy):")
    # start_month = input("[VEGAS] Please type the starting month for which you would like to pull data (1-12):")
    # start_day = input("[VEGAS] Please type the starting month for which you would like to pull data (1-31):")
    # numdays = input("[VEGAS] Please type the last month for which you would like to pull data (1-365):")
    # start_year = 2016
    # start_month = 9
    # start_day = 8
    # numdays = 110
    # # numdays = 130
    # base = datetime.datetime(int(start_year), int(start_month), int(start_day))
    # date_list = [base + datetime.timedelta(days=x) for x in range(0, int(numdays))]
    # for date_object in date_list:
    #     try:

    #         # print('year-> ',date_object.year)
    #         # print('month-> ',date_object.month)
    #         # print('\n')
    #         print(date_object.month, '-> ',monthrange(date_object.year, date_object.month)[1])
    #         # parse_to_csv_vegas(date_object)
    #     except AttributeError:
    #         print('wrong date'+str(date_object))
    #         pass


    # for i in range(14,14):
    parse_to_csv_vegas(str(15))